inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'

Metrics/BlockLength:
  Enabled: false

# This suggests awkward alignment, so disable it
Layout/RescueEnsureAlignment:
  Exclude:
    - 'app/models/email_signup/feed_url_validator.rb'
    - 'app/models/unpublishing.rb'
    - 'app/presenters/detailed_guide_presenter.rb'
    - 'app/presenters/detailed_guide_presenter.rb'

Style/EvalWithLocation:
  Exclude:
    - 'app/helpers/admin/edition_routes_helper.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'
    # Hopefully this file can be removed soon...
    - 'lib/migrate_assets_to_asset_manager.rb'
    - 'lib/tasks/scheduled_publishing.rake'

Rails/FindBy:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes
